# Generated by Django 5.2.9 on 2026-03-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifikasi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifikasiijazah",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
