# Generated by Django 5.2.12 on 2026-03-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifikasi", "0002_verifikasiijazah_file_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="verifikasiijazah", name="file_name",),
        migrations.AddField(
            model_name="verifikasiijazah",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="ijazah/"),
        ),
    ]
