# Generated by Django 5.2.12 on 2026-05-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifikasi", "0003_remove_verifikasiijazah_file_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verifikasiijazah",
            name="status",
            field=models.CharField(
                choices=[
                    ("MENUNGGU VERIFIKASI", "Menunggu"),
                    ("VALID", "Valid"),
                    ("TIDAK MEMENUHI SYARAT", "Tidak Valid"),
                    ("TIDAK TERDETEKSI", "Tidak Terdeteksi"),
                ],
                default="MENUNGGU VERIFIKASI",
                max_length=30,
            ),
        ),
    ]
