# Generated by Django 5.2.12 on 2026-05-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifikasi", "0004_alter_verifikasiijazah_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifikasiijazah",
            name="hasil_benar",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="verifikasiijazah",
            name="salah_tahun",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="verifikasiijazah",
            name="tidak_terbaca",
            field=models.BooleanField(default=False),
        ),
    ]
