# Generated by Django 5.2.12 on 2026-05-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifikasi", "0005_verifikasiijazah_hasil_benar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifikasiijazah",
            name="cer",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verifikasiijazah",
            name="nama_ocr",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="verifikasiijazah",
            name="wer",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
