# Generated by Django 5.2.12 on 2026-05-30 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifikasi", "0006_verifikasiijazah_cer_verifikasiijazah_nama_ocr_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="verifikasiijazah",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verifikasi",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
